### ISSUE TITLE
NICE!!!! - nuke.js VS sails.js + mithril

### ISSUE THREAD

**Issue by saniko** [FREEZX/nuke.js#2]
Hi, looks nice.
1. Besides the "tech stack" (that defaults only to mongoDB) how would you compare (DR;TL) both projects ?
2. Any sample project to lean from?
3. what is the road map?

Best

**Comment by FREEZX** [comment]
1. @saniko nuke.js is more of a 'boilerplate' project, and relies on several other great projects (primus, mongoose, express), while sails.js uses its own things (like waterline), so it's a bit more difficult to adapt if you need something different.
2. The whole repo is a sample project, and it contains example code.
3. I'll create a yeoman generator for the whole project, as well as modules (That would generate all needed front-end and back-end code for the entity you need). This will be somewhat similar to what mean.js [offers](http://meanjs.org/generator.html), and it will provide a great productivity boost. The other thing i'm planning is to create tests for everything.

**Comment by FREEZX** [comment]
I would also like to add that even though the default models work with mongodb you can probably easily switch to another ORM by modifying the config files.
